### ISSUE TITLE
Cookie keeps getting restored after being deleted?

### ISSUE THREAD

**Issue by j0hnk1m** [kevin51jiang/react-spotify-auth#4]
It seems as if when I am authenticated and I try to delete the cookie with a package like ```js-cookie``` or ```universal-cookie```, the cookie keeps getting restored. Sometimes when I try printing the value of spotifyAuthToken using
```javascript
console.log(Cookies.get('spotifyAuthToken'));
```

it logs ```undefined``` even when I clearly see the token under the Cookies section in developer tools. Why does this happen?

**Comment by kevin51jiang** [comment]
> the cookie keeps getting restored.

It might be getting restored if you're reloading the page, because if the access token is in the URL the library will automatically parse it.

Can you elaborate a bit more about the situation where it logs undefined when it shows up in dev tools?

**Comment by j0hnk1m** [comment]
Ah yes, that was the issue. Even if I cleared my cookies, because the URL had the access token, it was being reloaded by the library. I  ended up doing a force navigate (gatsby), and that fixed it! 

Thank you!
