### ISSUE TITLE
CORS  issue when embedding  app  in iframe

### ISSUE THREAD

**Issue by ffleandro** [kevin51jiang/react-spotify-auth#55]
I  can't use this library in a react  app embedded  in an iframe due to  CORS issues.
Why does `getHash` needs to access `window.parent`?
https://github.com/kevin51jiang/react-spotify-auth/blob/a280a515847837faacf2b3362ef4417f5fecb226/src/getHash.js#L3

`Uncaught DOMException: Blocked a frame with origin "my-iframe-source-url" from accessing a cross-origin frame.`

**Comment by ffleandro** [comment]
Can we  use `window.location.hash` instead of `window.parent.location.hash `.
Just checked here locally and it seems to return the same result.

**Comment by kevin51jiang** [comment]
Sounds good I'll change it

**Comment by ffleandro** [comment]
Spotify also doesn't allow embedding their SSO form in an  iframe.
I've added this feature and can push all of this into a PR for your review today.

**Comment by kevin51jiang** [comment]
Fixed by #56
